spring:

    data:
        mongodb:
            username: root
            password: pass
            host: localhost
            port: 27019
            database: customer
            authentication-database: admin

server:
    port: 8090