spring:
    datasource:
        url: jdbc:postgresql://localhost:5430/payment
        username: root
        password: pass
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: validate
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect

    kafka:
        producer:
            key-serializer: org,apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            bootstrap-servers: localhost:9092
            properties:
                spring.json.type.mapping: paymentNotification:com.bloodxxet.ecommerce.notification.PaymentNotification

server:
    port: 8060