services:
    postgres:
        container_name: postgresql
        image: postgres:16.3
        restart: "no"
        ports:
            - "5432:5432"
        volumes:
            - postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: bloodxxet
            POSTGRES_PASSWORD: bloodxxet
            PGDATA: /var/lib/postgresql/data
        healthcheck:
            test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
            interval: 10s
            timeout: 5s
            start_period: 10s
            retries: 5
        networks:
            - microservices-net

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:8.9
        restart: "no"
        ports:
            - "5050:80"
        volumes:
            - pgadmin:/var/lib/pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
            PGADMIN_CONFIG_SERVER_MODE: "False"
        healthcheck:
            test: wget --no-verbose --tries=1 --spider http://localhost:80/misc/ping || exit -1
            interval: 10s
            timeout: 5s
            start_period: 10s
            retries: 5
        networks:
            - microservices-net

    zipkin:
        container_name: zipkin
        image: openzipkin/zipkin
        ports:
            - "9411:9411"
        networks:
            - microservices-net

    mongo:
        image: mongo:latest
        container_name: mongo
        restart: unless-stopped
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: pass
            MONGO_INITDB_DATABASE: mydb
        healthcheck:
            test: echo 'db.runCommand({serverStatus:1}).ok' | mongosh admin -u $$MONGO_INITDB_ROOT_USERNAME -p $$MONGO_INITDB_ROOT_PASSWORD --quiet | grep 1
            interval: 10s
            timeout: 5s
            start_period: 10s
            retries: 5

    mongo-express:
        container_name: mongo-express
        image: mongo-express:latest
        restart: always
        ports:
            - "8081:8081"
        environment:
            ME_CONFIG_BASICAUTH_USERNAME: root
            ME_CONFIG_BASICAUTH_PASSWORD: root
            ME_CONFIG_MONGODB_URL: mongodb://root:pass@mongo:27017/
        depends_on:
            - mongo

networks:
    microservices-net:
        driver: bridge

volumes:
    postgres:
    pgadmin:
    mongo_data: