services:
    postgresql:
        container_name: ms_pg_sql
        image: postgres
        environment:
            POSTGRES_USER: bloodxxet
            POSTGRES_PASSWORD: bloodxxet
            PGDATA: /data/postgres
        volumes:
            - postgres:/data/postgres
        ports:
            - "5432:5432"
        networks:
            - microservices-net
        restart: unless-stopped

    pgadmin:
        container_name: ms_pgadmin
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
            PGADMIN_CONFIG_SERVER_MODE: 'False'
        volumes:
            - pgadmin:/var/lib/pgadmin
        ports:
            - "5050:80"
        networks:
            - microservices-net
        restart: unless-stopped

    zipkin:
        container_name: zipkin
        image: openzipkin/zipkin
        ports:
            - "9411:9411"
        networks:
            - microservices-net

    mongo:
        image: mongo:latest
        restart: unless-stopped
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: pass
            MONGO_INITDB_DATABASE: mydb
        healthcheck:
            test: echo 'db.runCommand({serverStatus:1}).ok' | mongosh admin -u $$MONGO_INITDB_ROOT_USERNAME -p $$MONGO_INITDB_ROOT_PASSWORD --quiet | grep 1
            interval: 10s
            timeout: 5s
            start_period: 10s
            retries: 5

    mongo-express:
        image: mongo-express:latest
        restart: always
        ports:
            - "8081:8081"
        environment:
            ME_CONFIG_BASICAUTH_USERNAME: root
            ME_CONFIG_BASICAUTH_PASSWORD: root
            ME_CONFIG_MONGODB_URL: mongodb://root:pass@mongo:27017/
        depends_on:
            - mongo

networks:
    microservices-net:
        driver: bridge

volumes:
    postgres:
    pgadmin:
    mongo_data: