spring:

    config:
        import: optional:configserver:http://localhost:8888

    datasource:
        url: jdbc:postgresql://localhost:5430/order
        username: root
        password: pass
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: create
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect

    kafka:
        producer:
            bootstrap-servers: localhost:9092
            key-serializer: org,apache.kafka.common.serialization.SpringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

            properties:
                spring.json.type.mapping: orderConfirmation:com.bloodxxet.ecommerce.kafka.OrderConfirmation

server:
    port: 8070


application:
    config:
        customer-url: http://localhost:8222/api/v1/customers
        product-url: http://localhost:8222/api/v1/products
        payment-url: http://localhost:8222/api/v1/payments